[2023-11-24T18:22:43.501+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.send_success_email manual__2023-11-24T18:21:53.741864+00:00 [queued]>
[2023-11-24T18:22:43.511+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.send_success_email manual__2023-11-24T18:21:53.741864+00:00 [queued]>
[2023-11-24T18:22:43.512+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-24T18:22:43.525+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): send_success_email> on 2023-11-24 18:21:53.741864+00:00
[2023-11-24T18:22:43.530+0000] {standard_task_runner.py:57} INFO - Started process 168 to run task
[2023-11-24T18:22:43.532+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'send_success_email', 'manual__2023-11-24T18:21:53.741864+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpk9weydao']
[2023-11-24T18:22:43.536+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask send_success_email
[2023-11-24T18:22:43.576+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.send_success_email manual__2023-11-24T18:21:53.741864+00:00 [running]> on host d2fa4fd9c0bc
[2023-11-24T18:22:43.776+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='send_success_email' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T18:21:53.741864+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T18:21:53.741864+00:00'
[2023-11-24T18:22:43.785+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-11-24T18:22:43.786+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2023-11-24T18:22:43.787+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-11-24T18:22:43.788+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-11-24T18:22:43.795+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=send_success_email, execution_date=20231124T182153, start_date=20231124T182243, end_date=20231124T182243
[2023-11-24T18:22:43.806+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task send_success_email ([Errno 99] Cannot assign requested address; 168)
[2023-11-24T18:22:43.827+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T18:22:43.840+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
