[2023-11-15T20:49:23.026+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PROJET.create_table manual__2023-11-15T20:49:19.901024+00:00 [queued]>
[2023-11-15T20:49:23.033+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PROJET.create_table manual__2023-11-15T20:49:19.901024+00:00 [queued]>
[2023-11-15T20:49:23.035+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-15T20:49:23.047+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table> on 2023-11-15 20:49:19.901024+00:00
[2023-11-15T20:49:23.056+0000] {standard_task_runner.py:57} INFO - Started process 2539 to run task
[2023-11-15T20:49:23.063+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PROJET', 'create_table', 'manual__2023-11-15T20:49:19.901024+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Untitled-1.py', '--cfg-path', '/tmp/tmp6vcswa3w']
[2023-11-15T20:49:23.065+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask create_table
[2023-11-15T20:49:23.121+0000] {task_command.py:416} INFO - Running <TaskInstance: PROJET.create_table manual__2023-11-15T20:49:19.901024+00:00 [running]> on host a367eff75e40
[2023-11-15T20:49:23.160+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'create_table', field 'sql'. Template: 'sql/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-11-15T20:49:23.162+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-11-15T20:49:23.171+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=PROJET, task_id=create_table, execution_date=20231115T204919, start_date=20231115T204923, end_date=20231115T204923
[2023-11-15T20:49:23.179+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task create_table (sql/create_table.sql; 2539)
[2023-11-15T20:49:23.195+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-15T20:49:23.215+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
