[2023-11-21T19:31:55.744+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform manual__2023-11-21T19:31:54.347089+00:00 [queued]>
[2023-11-21T19:31:55.756+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform manual__2023-11-21T19:31:54.347089+00:00 [queued]>
[2023-11-21T19:31:55.757+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T19:31:55.774+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_and_transform> on 2023-11-21 19:31:54.347089+00:00
[2023-11-21T19:31:55.786+0000] {standard_task_runner.py:57} INFO - Started process 2509 to run task
[2023-11-21T19:31:55.792+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'extract_and_transform', 'manual__2023-11-21T19:31:54.347089+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp4_7w449e']
[2023-11-21T19:31:55.797+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask extract_and_transform
[2023-11-21T19:31:55.864+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.extract_and_transform manual__2023-11-21T19:31:54.347089+00:00 [running]> on host 726cce66553f
[2023-11-21T19:31:56.110+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='extract_and_transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T19:31:54.347089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T19:31:54.347089+00:00'
[2023-11-21T19:31:56.383+0000] {logging_mixin.py:151} INFO -   Code tranches         age
0             0   tous ages
1             A     0-4 ans
2             B    5-14 ans
3             C   15-44 ans
4             D   45-64 ans
5             E   65-74 ans
6             F  75 et plus
[2023-11-21T19:31:56.585+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-21T19:31:56.782+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table tranches_dage because other objects depend on it
DETAIL:  constraint passages_corona_sursaud_cl_age_corona_fkey on table passages_corona depends on table tranches_dage
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL.py", line 47, in extract_and_transform
    df_tranches_dage.to_sql('tranches_dage', postgres_sql_upload.get_sqlalchemy_engine(), if_exists='replace', chunksize=1000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1910, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1814, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 907, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1963, in drop_table
    self.get_table(table_name, schema).drop(bind=self.con)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1106, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table tranches_dage because other objects depend on it
DETAIL:  constraint passages_corona_sursaud_cl_age_corona_fkey on table passages_corona depends on table tranches_dage
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE tranches_dage]
(Background on this error at: https://sqlalche.me/e/14/2j85)
[2023-11-21T19:31:56.802+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=extract_and_transform, execution_date=20231121T193154, start_date=20231121T193155, end_date=20231121T193156
[2023-11-21T19:31:56.820+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task extract_and_transform ((psycopg2.errors.DependentObjectsStillExist) cannot drop table tranches_dage because other objects depend on it
DETAIL:  constraint passages_corona_sursaud_cl_age_corona_fkey on table passages_corona depends on table tranches_dage
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE tranches_dage]
(Background on this error at: https://sqlalche.me/e/14/2j85); 2509)
[2023-11-21T19:31:56.852+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T19:31:56.885+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
