[2023-11-19T19:17:01.509+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T19:13:49.615603+00:00 [queued]>
[2023-11-19T19:17:01.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T19:13:49.615603+00:00 [queued]>
[2023-11-19T19:17:01.519+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-19T19:17:01.527+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-19 19:13:49.615603+00:00
[2023-11-19T19:17:01.553+0000] {standard_task_runner.py:57} INFO - Started process 942 to run task
[2023-11-19T19:17:01.557+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet', 'Extract', 'manual__2023-11-19T19:13:49.615603+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_sample.py', '--cfg-path', '/tmp/tmpnh8nbc0p']
[2023-11-19T19:17:01.561+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask Extract
[2023-11-19T19:17:01.599+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet.Extract manual__2023-11-19T19:13:49.615603+00:00 [running]> on host 4a664210de45
[2023-11-19T19:17:03.408+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T19:13:49.615603+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-19T19:13:49.615603+00:00'
[2023-11-19T19:17:04.045+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_sample.py:16: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_sos, delimiter=';', dtype={'Code tranches d\'age': str})

[2023-11-19T19:17:06.469+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_sample.py", line 43, in data_transform_and_load
    df_urgences['columns_to_convert'] = df_urgences[columns_to_convert].apply(pd.to_numeric, errors='coerce')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3940, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4094, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column columns_to_convert
[2023-11-19T19:17:06.626+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet, task_id=Extract, execution_date=20231119T191349, start_date=20231119T191701, end_date=20231119T191706
[2023-11-19T19:17:06.685+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task Extract (Cannot set a DataFrame with multiple columns to the single column columns_to_convert; 942)
[2023-11-19T19:17:06.778+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T19:17:06.802+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
