[2023-11-19T19:14:09.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T19:13:49.615603+00:00 [queued]>
[2023-11-19T19:14:09.797+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T19:13:49.615603+00:00 [queued]>
[2023-11-19T19:14:09.798+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-19T19:14:09.840+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-19 19:13:49.615603+00:00
[2023-11-19T19:14:09.910+0000] {standard_task_runner.py:57} INFO - Started process 899 to run task
[2023-11-19T19:14:09.920+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet', 'Extract', 'manual__2023-11-19T19:13:49.615603+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_sample.py', '--cfg-path', '/tmp/tmp732yc252']
[2023-11-19T19:14:09.928+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask Extract
[2023-11-19T19:14:10.024+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet.Extract manual__2023-11-19T19:13:49.615603+00:00 [running]> on host 4a664210de45
[2023-11-19T19:14:12.785+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T19:13:49.615603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-19T19:13:49.615603+00:00'
[2023-11-19T19:14:13.000+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_sample.py:16: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_sos, delimiter=';', dtype={'Code tranches d\'age': str})

[2023-11-19T19:14:13.160+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_sample.py", line 33, in data_transform_and_load
    df = df.dropna()
UnboundLocalError: local variable 'df' referenced before assignment
[2023-11-19T19:14:13.170+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet, task_id=Extract, execution_date=20231119T191349, start_date=20231119T191409, end_date=20231119T191413
[2023-11-19T19:14:13.179+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task Extract (local variable 'df' referenced before assignment; 899)
[2023-11-19T19:14:13.227+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T19:14:13.260+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
