[2023-11-21T20:35:13.316+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.create_key manual__2023-11-21T20:34:54.398946+00:00 [queued]>
[2023-11-21T20:35:13.325+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.create_key manual__2023-11-21T20:34:54.398946+00:00 [queued]>
[2023-11-21T20:35:13.326+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T20:35:13.339+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_key> on 2023-11-21 20:34:54.398946+00:00
[2023-11-21T20:35:13.344+0000] {standard_task_runner.py:57} INFO - Started process 3996 to run task
[2023-11-21T20:35:13.347+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'create_key', 'manual__2023-11-21T20:34:54.398946+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp7dngd3q5']
[2023-11-21T20:35:13.350+0000] {standard_task_runner.py:85} INFO - Job 125: Subtask create_key
[2023-11-21T20:35:13.410+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.create_key manual__2023-11-21T20:34:54.398946+00:00 [running]> on host 726cce66553f
[2023-11-21T20:35:13.657+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='create_key' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T20:34:54.398946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T20:34:54.398946+00:00'
[2023-11-21T20:35:13.658+0000] {sql.py:274} INFO - Executing: ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_dep_fkey
FOREIGN KEY (dep)
REFERENCES departements (num_dep);


ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_dep_fkey
FOREIGN KEY (sursaud_cl_age_corona)
REFERENCES tranches_dage (Code_tranches_dage);
[2023-11-21T20:35:13.668+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-21T20:35:13.677+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-21T20:35:13.689+0000] {sql.py:418} INFO - Running statement: ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_dep_fkey
FOREIGN KEY (dep)
REFERENCES departements (num_dep);


ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_dep_fkey
FOREIGN KEY (sursaud_cl_age_corona)
REFERENCES tranches_dage (Code_tranches_dage);, parameters: None
[2023-11-21T20:35:13.694+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "departements"

[2023-11-21T20:35:13.703+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=create_key, execution_date=20231121T203454, start_date=20231121T203513, end_date=20231121T203513
[2023-11-21T20:35:13.716+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 125 for task create_key (there is no unique constraint matching given keys for referenced table "departements"
; 3996)
[2023-11-21T20:35:13.762+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T20:35:13.784+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
