[2023-11-19T19:14:05.422+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet.create_table manual__2023-11-19T19:13:49.615603+00:00 [queued]>
[2023-11-19T19:14:05.437+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet.create_table manual__2023-11-19T19:13:49.615603+00:00 [queued]>
[2023-11-19T19:14:05.438+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-19T19:14:05.456+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table> on 2023-11-19 19:13:49.615603+00:00
[2023-11-19T19:14:05.468+0000] {standard_task_runner.py:57} INFO - Started process 896 to run task
[2023-11-19T19:14:05.474+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet', 'create_table', 'manual__2023-11-19T19:13:49.615603+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_sample.py', '--cfg-path', '/tmp/tmpd50y_0tu']
[2023-11-19T19:14:05.478+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask create_table
[2023-11-19T19:14:05.546+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet.create_table manual__2023-11-19T19:13:49.615603+00:00 [running]> on host 4a664210de45
[2023-11-19T19:14:06.530+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'create_table', field 'sql'. Template: 'sql/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-11-19T19:14:06.535+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-11-19T19:14:06.559+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet, task_id=create_table, execution_date=20231119T191349, start_date=20231119T191405, end_date=20231119T191406
[2023-11-19T19:14:06.578+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task create_table (sql/create_table.sql; 896)
[2023-11-19T19:14:06.685+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T19:14:07.064+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
