[2023-11-19T19:13:53.847+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T18:09:34.683703+00:00 [queued]>
[2023-11-19T19:13:53.857+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T18:09:34.683703+00:00 [queued]>
[2023-11-19T19:13:53.857+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-19T19:13:53.884+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-19 18:09:34.683703+00:00
[2023-11-19T19:13:53.900+0000] {standard_task_runner.py:57} INFO - Started process 885 to run task
[2023-11-19T19:13:53.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet', 'Extract', 'manual__2023-11-19T18:09:34.683703+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_sample.py', '--cfg-path', '/tmp/tmpdezhtg0u']
[2023-11-19T19:13:53.936+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask Extract
[2023-11-19T19:13:54.197+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet.Extract manual__2023-11-19T18:09:34.683703+00:00 [running]> on host 4a664210de45
[2023-11-19T19:13:59.532+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T18:09:34.683703+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-19T18:09:34.683703+00:00'
[2023-11-19T19:14:00.375+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_sample.py:16: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_sos, delimiter=';', dtype={'Code tranches d\'age': str})

[2023-11-19T19:14:01.026+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_sample.py", line 33, in data_transform_and_load
    df = df.dropna()
UnboundLocalError: local variable 'df' referenced before assignment
[2023-11-19T19:14:01.351+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet, task_id=Extract, execution_date=20231119T180934, start_date=20231119T191353, end_date=20231119T191401
[2023-11-19T19:14:01.528+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task Extract (local variable 'df' referenced before assignment; 885)
[2023-11-19T19:14:01.720+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T19:14:02.042+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
